apiVersion: v1
kind: Service
metadata:
  name: nginx-canary-service
  namespace: k8s-deployments
spec:
  selector:
    app: nginx
    version: canary  # ✅ Now only selects Canary pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer