# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-blue-green-service
#   namespace: k8s-deployments
# spec:
#   selector:
#     app: nginx
#     version: blue  # 🔵 Start by routing traffic to "blue"
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-green-service
  namespace: k8s-deployments
spec:
  selector:
    app: nginx
    version: green  # 🟩 Switch to green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer